# Generated by Django 4.2.4 on 2023-08-17 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relaciones', '0002_tipocombustible_fabricante_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorEjecutivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Director Ejecutivo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fabricante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='relaciones.fabricante')),
            ],
        ),
    ]
