# Generated by Django 4.2.4 on 2023-08-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='emp_correo',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='emp_designacion',
            field=models.CharField(choices=[('Project Manager', 'Project Manager'), ('Programador', 'Programador'), ('Soporte Técnico', 'Soporte Técnico'), ('Desarrollador Web', 'Desarrollador Web')], max_length=150, verbose_name='Designación'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='emp_id',
            field=models.CharField(max_length=3, verbose_name='Id empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='emp_nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
    ]
