# Generated by Django 4.0.5 on 2023-08-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migraciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preciohistoricovehiculos',
            name='color',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
        migrations.AlterField(
            model_name='preciohistoricovehiculos',
            name='modelo',
            field=models.TextField(verbose_name='Modelo'),
        ),
    ]
